---
version: '3'

tasks:
  analyze-frontend:
    desc: Analyze frontend bundle
    env:
      VITE_BUNDLE_ANALYZE: 'true'
    dir: "./frontend/"
    cmds:
      - bun vite build

  build:
    desc: Build (frontend; server)
    cmds:
      - task: build-frontend-compress
      - task: build-server

  # TODO: Experimental
  build-app:
    desc: Build application
    env:
      CGO_ENABLED: '{{if eq .RACE "true"}}1{{else}}0{{end}}'
    vars:
      FLAG_RACE: '{{if eq .RACE "true"}}-race {{end}}'
      FLAGS: '{{.FLAG_RACE}}{{if eq .DEBUG "true"}}-debug{{end}}-ldflags="-w -s" -m -trimpath -nosyncgomod -skipbindings'
    cmds:
      - wails build {{.FLAGS}}

  build-server:
    desc: Build server
    env:
      CGO_ENABLED: '{{if eq .RACE "true"}}1{{else}}0{{end}}'
    vars:
      FLAG_RACE: '{{if eq .RACE "true"}}-race {{end}}'
      FLAGS: '{{.FLAG_RACE}}{{if eq .DEBUG "true"}}-gcflags="all=-N -l"{{else}}-ldflags="-w -s" -trimpath{{end}}'
      OUTPUT: '{{if eq .GOOS "windows"}}./build/bin/server.exe{{else}}./build/bin/server{{end}}'
    cmds:
      - go build {{.FLAGS}} -o {{.OUTPUT}} ./build/server/

  build-frontend:
    desc: Build frontend
    dir: "./frontend/"
    cmds:
      - task: clean-dist-frontend
      - bun vite build
      - task: x-script-minify

  build-frontend-compress:
    desc: Build frontend (with compression)
    dir: "./frontend/"
    cmds:
      - task: build-frontend
      - task: x-script-compress

  clean:
    desc: Clean project environment
    cmds:
      - go clean
      - task: clean-app
      - task: clean-server
      - task: clean-frontend

  clean-git:
    desc: Clean GIT (careful)
    cmds:
      - task: clean-git-untracked
      - task: clean-git-gc
      - task: clean-git-hooks

  clean-git-gc:
    cmds:
      - git gc --aggressive --prune

  clean-git-hooks:
    cmds:
      - bun exec "rm -rf ./.git/hooks/"

  clean-git-untracked:
    cmds:
      - git clean -d -x -i

  clean-app:
    desc: Clean application
    dir: "./frontend/"
    cmds:
      - task: clean-dist-go
      - bun exec "rm -rf ./wailsjs/"

  clean-server:
    desc: Clean Go
    cmds:
      - task: clean-dist-go

  clean-frontend:
    desc: Clean frontend
    dir: "./frontend/"
    cmds:
      - task: clean-dist-frontend
      - bun exec "rm -rf ./node_modules/"

  clean-dist:
    desc: Cleans all builds output
    cmds:
      - task: clean-dist-go
      - task: clean-dist-frontend

  clean-dist-go:
    desc: Cleans the Go build output
    dir: "./build/"
    cmds:
      - bun exec "rm -rf ./bin/"

  clean-dist-frontend:
    desc: Cleans the frontend build output
    dir: "./frontend/"
    cmds:
      - bun exec "rm -rf ./dist/"

  fix:
    desc: Run all formatters
    cmds:
      - task: fix-go
      - task: fix-frontend

  fix-go:
    desc: Run Go formatters
    cmds:
      - go fmt

  fix-frontend:
    desc: Run frontend formatters
    dir: "./frontend/"
    cmds:
      - bun biome check --write
      - bun sort-package-json --quiet

  install:
    desc: Install all dependencies
    cmds:
      - task: install-go
      - task: install-frontend

  install-ci:
    cmds:
      - task: install-go
      - task: install-frontend-ci

  install-frontend:
    desc: Install frontend dependencies
    dir: "./frontend/"
    cmds:
      - bun install

  install-frontend-ci:
    dir: "./frontend/"
    cmds:
      - bun install --frozen-lockfile

  install-go:
    desc: Install Go dependencies
    cmds:
      - go mod download

  lint:
    desc: Run all linters
    cmds:
      - task: lint-go
      - task: lint-frontend

  lint-frontend:
    desc: Run frontend linters
    dir: "./frontend/"
    cmds:
      - bun biome lint
      - bun tsc --noEmit

  lint-go:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  start:
    desc: Start (frontend; server)
    cmds:
      - task: build-frontend-compress
      - task: start-server

  start-server:
    desc: Start the server (requires built frontend)
    cmds:
      - go run ./build/server/

  start-dev:
    desc: Start in HMR
    dir: "./frontend/"
    cmds:
      - bun vite dev

  tidy:
    desc: Tidy all
    cmds:
      - task: tidy-go
      - task: tidy-frontend

  tidy-frontend:
    desc: Tidy frontend
    dir: "./frontend/"
    cmds:
      - bun exec "rm -f bun.lock"
      - bun install -f

  tidy-go:
    desc: Tidy Go
    cmds:
      - go mod tidy

  x-script-minify:
    internal: true
    cmds:
      - go run ./build/scripts/minify/

  x-script-compress:
    internal: true
    cmds:
      - go run ./build/scripts/compress/
