---
version: '3'

tasks:
  build:
    desc: Builds "www/" and the server
    cmds:
      - task: build-www
      - task: build-server

  build-server:
    desc: Build the server
    vars:
      FLAG_RACE: '{{if eq .RACE "true"}}-race{{end}}'
      FLAGS: '{{if eq .DEBUG "true"}}-gcflags="all=-N -l" {{.FLAG_RACE}}{{else}}-ldflags="-w -s" -trimpath {{.FLAG_RACE}}{{end}}'
      OUTPUT: '{{if eq .GOOS "windows"}}./dist/server.exe{{else}}./dist/server{{end}}'
    cmds:
      - go build {{.FLAGS}} -o {{.OUTPUT}} ./

  build-www:
    desc: Build "www/"
    cmds:
      - task: clean-dist-www
      - bun --cwd=./www/ vite build
      - task: x-script-www-minify
      - task: x-script-www-compress

  build-www-debug:
    cmds:
      - task: clean-dist-www
      - NODE_ENV=development bun --cwd=./www/ vite build

  clean:
    desc: Cleans "www/" and the server
    cmds:
      - task: clean-www
      - task: clean-server

  clean-git:
    desc: Clean GIT (careful)
    cmds:
      - task: clean-git-untracked
      - task: clean-git-gc
      - task: clean-git-hooks

  clean-git-gc:
    cmds:
      - git gc --aggressive --prune

  clean-git-hooks:
    cmds:
      - bun exec "rm -rf ./.git/hooks/"

  clean-git-untracked:
    cmds:
      - git clean -d -x -i

  clean-server:
    desc: Clean the server
    cmds:
      - task: clean-dist-server
      - go clean

  clean-www:
    desc: Clean "www/"
    cmds:
      - task: clean-dist-www
      - bun --cwd=./www/ exec "rm -rf ./node_modules/"
      # TODO: rollup-plugin-visualizer issue
      - bun --cwd=./www/ exec "rm -f bundle.html"

  clean-dist:
    desc: Cleans only dist from "www/" and the server
    cmds:
      - task: clean-dist-www
      - task: clean-dist-server

  clean-dist-server:
    desc: Cleans only dist from the server
    cmds:
      - bun exec "rm -rf ./dist/"

  clean-dist-www:
    desc: Cleans only dist from "www/"
    cmds:
      - bun --cwd=./www/ exec "rm -rf ./dist/"

  dev-www:
    desc: Run "www/" in HMR mode
    cmds:
      - bun --cwd=./www/ vite dev

  fix:
    desc: Run formatters on "www/" and the server
    cmds:
      - task: fix-www
      - task: fix-server

  fix-server:
    desc: Run formatters on the server
    cmds:
      - go fmt

  fix-www:
    desc: Run formatters on "www/"
    cmds:
      - bun --cwd=./www/ biome check --write
      - bun --cwd=./www/ sort-package-json --quiet

  install:
    desc: Installs dependencies for "www/" and the server
    cmds:
      - task: install-www
      - task: install-server

  install-ci:
    cmds:
      - task: install-www-ci
      - task: install-server

  install-server:
    desc: Install dependencies for the server
    cmds:
      - go mod download

  install-www:
    desc: Install dependencies for "www/"
    cmds:
      - bun --cwd=./www/ install

  install-www-ci:
    cmds:
      - bun --cwd=./www/ install --frozen-lockfile

  lint:
    desc: Run linters on "www/" and the server
    cmds:
      - task: lint-www
      - task: lint-server

  lint-server:
    desc: Run linters on the server
    cmds:
      - golangci-lint run

  lint-www:
    desc: Run linters on "www/"
    cmds:
      - bun --cwd=./www/ biome lint
      - bun --cwd=./www/ tsc --noEmit

  start-server:
    desc: Start the server (requires building "www/")
    cmds:
      - go run ./

  start-www:
    desc: Start "www/" in preview mode (requires building "www/")
    cmds:
      - bun --cwd=./www/ vite preview

  tidy:
    desc: Tidy "www/" and the server
    cmds:
      - task: tidy-www
      - task: tidy-server

  tidy-server:
    desc: Tidy the server
    cmds:
      - go mod tidy

  tidy-www:
    desc: Tidy "www/"
    cmds:
      - bun --cwd=./www/ exec "rm -f bun.lock"
      - bun --cwd=./www/ install -f

  x-script-www-minify:
    internal: true
    cmds:
      - go run ./www/scripts/minify/main.go

  x-script-www-compress:
    internal: true
    cmds:
      - go run ./www/scripts/compress/main.go
