---
name: CD
on:
  workflow_dispatch:
    inputs:
      artifact-action:
        description: Artifact action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release

      image-action:
        description: Container image action
        type: choice
        required: true
        default: none
        options:
          - none
          - build
          - build-release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  artifact:
    if: github.repository_owner == 'jspaste' && inputs.artifact-action != 'none'
    name: Release artifact
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: "audit"

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: "false"

      - name: Setup mise-en-place
        uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1

      - name: Save context
        id: ctx
        env:
          CTX_BRANCH: ${{ github.head_ref || github.ref_name }}
          CTX_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Save tags
        id: tags
        env:
          BRANCH: ${{ steps.ctx.outputs.branch }}
          SHA_SHORT: ${{ steps.ctx.outputs.sha_short }}
        run: |
          TIMESTAMP="$(date +%Y.%m.%d)"

          if [[ "${BRANCH}" == "stable" ]]; then
            TAG="latest"
          else
            TAG="snapshot"
          fi

          echo "tag=${TAG}" >>"$GITHUB_OUTPUT"
          echo "extended=${TIMESTAMP}-${SHA_SHORT}" >>"$GITHUB_OUTPUT"

      - name: Build frontend
        run: mise run build:frontend

      - name: Build artifact
        run: |
          GOOS=darwin GOARCH=arm64 mise run build:server
          chmod 755 ./dist/server
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ server | xz -z -6 >./dist/frontend_${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz
          tar -tJf ./dist/frontend_${{ steps.tags.outputs.tag }}_darwin-arm64.tar.xz >/dev/null

          GOOS=linux GOARCH=amd64 mise run build:server
          chmod 755 ./dist/server
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ server | xz -z -6 >./dist/frontend_${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz
          tar -tJf ./dist/frontend_${{ steps.tags.outputs.tag }}_linux-amd64.tar.xz >/dev/null

          GOOS=linux GOARCH=arm64 mise run build:server
          chmod 755 ./dist/server
          tar -c --owner=0 --group=0 --mtime='now' --utc .env.example LICENSE README.md -C ./dist/ server | xz -z -6 >./dist/frontend_${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz
          tar -tJf ./dist/frontend_${{ steps.tags.outputs.tag }}_linux-arm64.tar.xz >/dev/null

          GOOS=windows GOARCH=amd64 mise run build:server
          chmod 755 ./dist/server.exe
          zip -j -X -9 -l -o ./dist/frontend_${{ steps.tags.outputs.tag }}_windows-amd64.zip .env.example LICENSE README.md ./dist/server.exe
          zip -T ./dist/frontend_${{ steps.tags.outputs.tag }}_windows-amd64.zip

      - if: inputs.artifact-action == 'build-release'
        name: Release artifact
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          name: "${{ steps.tags.outputs.extended }}"
          tag: "${{ steps.tags.outputs.extended }}"
          artifacts: "dist/*.tar.xz,dist/*.zip"
          makeLatest: "true"
          prerelease: "${{ steps.ctx.outputs.branch != 'stable' }}"
          generateReleaseNotes: "${{ steps.ctx.outputs.branch == 'stable' }}"

      - if: inputs.artifact-action == 'build-release'
        name: Attest artifact
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: |
            dist/*.tar.xz
            dist/*.zip

  container-release:
    if: github.repository_owner == 'jspaste' && inputs.image-action != 'none'
    name: Release container image
    runs-on: ubuntu-latest
    outputs:
      tags: "${{ steps.image.outputs.tags }}"
      digest: "${{ steps.release.outputs.digest }}"
      registries: "${{ steps.release.outputs.registries }}"

    permissions:
      packages: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: "audit"

      - name: Setup podman
        env:
          PODMAN_VERSION: "v5.8.2"
        run: |
          sudo apt-get purge -y podman runc crun conmon

          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz"
          curl -fsSLO "https://github.com/mgoltzsche/podman-static/releases/download/${{ env.PODMAN_VERSION }}/podman-linux-amd64.tar.gz.asc"
          gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 0CCF102C4F95D89E583FF1D4F8B5AF50344BB503
          gpg --batch --verify "podman-linux-amd64.tar.gz.asc" "podman-linux-amd64.tar.gz"

          tar -xzf "podman-linux-amd64.tar.gz"
          sudo cp -rfv ./podman-linux-amd64/etc/. /etc/
          sudo cp -rfv ./podman-linux-amd64/usr/. /usr/

          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: "false"

      - name: Save context
        id: ctx
        env:
          CTX_BRANCH: ${{ github.head_ref || github.ref_name }}
          CTX_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Login to GHCR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: Build container image
        id: image
        env:
          GHA_BRANCH: "${{ steps.ctx.outputs.branch }}"
          GHA_SHA: "${{ steps.ctx.outputs.sha }}"
          GHA_SHA_SHORT: "${{ steps.ctx.outputs.sha_short }}"
          GHA_CONTAINER_ORGANIZATION: "jspaste"
          GHA_CONTAINER_IMAGE: "frontend"
        run: ./.github/scripts/build-container.sh

      - if: inputs.image-action == 'build-release'
        name: Release container image
        id: release
        env:
          GHA_TAG: "${{ steps.image.outputs.tags }}"
          GHA_REGISTRY: "ghcr.io docker.io"
          GHA_CONTAINER_ORGANIZATION: "jspaste"
          GHA_CONTAINER_IMAGE: "frontend"
          GHA_REGISTRY_ACCOUNT_NAME: "${{ github.repository_owner }} ${{ secrets.DOCKER_USER }}"
          GHA_REGISTRY_ACCOUNT_TOKEN: "${{ secrets.GITHUB_TOKEN }} ${{ secrets.DOCKER_TOKEN }}"
        run: ./.github/scripts/release-container.sh

  container-attest:
    if: github.repository_owner == 'jspaste' && inputs.image-action == 'build-release'
    name: Attest container image
    runs-on: ubuntu-latest
    needs: container-release
    strategy:
      matrix:
        registry: ${{ fromJson(needs.container-release.outputs.registries) }}

    permissions:
      attestations: write
      id-token: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: "audit"

      - name: Attest image
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-name: "${{ matrix.registry }}/jspaste/frontend"
          subject-digest: "${{ needs.container-release.outputs.digest }}"
