name: CI

on:
    pull_request:
        branches: [stable]
        types: [opened, synchronize]

jobs:
    avoid_redundancy_lint_pretty_and_cache_deps:
        runs-on: ubuntu-22.04
        permissions: write-all
        steps:
            - name: Cancel Previous Redundant Builds
              uses: styfle/cancel-workflow-action@0.11.0
              with:
                  access_token: ${{ github.token }}

            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v4
              with:
                  cache: 'pnpm'
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Lint
              continue-on-error: true
              run: pnpm run lint

            - name: Prettify code
              uses: creyD/prettier_action@v4.3
              with:
                  same_commit: true
                  prettier_options: . --write

    build:
        needs: [avoid_redundancy_lint_pretty_and_cache_deps]
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.pull_request.head.ref }}

            - uses: pnpm/action-setup@v2

            - uses: actions/setup-node@v4
              with:
                  cache: 'pnpm'
                  node-version: 20

            - name: Install dependencies
              run: pnpm install

            - name: Build
              run: pnpm run build
