---
name: CI
on:
  merge_group:
  pull_request:
    branches:
      - dev
    paths-ignore:
      - '*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.ctx.outputs.branch }}
      sha: ${{ steps.ctx.outputs.sha }}
      sha_short: ${{ steps.ctx.outputs.sha_short }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: "audit"

      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: "false"

      - name: Setup mise-en-place
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1

      - name: Save context information
        id: ctx
        env:
          CTX_BRANCH: ${{ github.head_ref || github.ref_name }}
          CTX_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          echo "branch=${CTX_BRANCH}" >>"$GITHUB_OUTPUT"
          echo "sha=${CTX_SHA}" >>"$GITHUB_OUTPUT"
          echo "sha_short=${CTX_SHA::7}" >>"$GITHUB_OUTPUT"

      - name: Build frontend
        run: mise run build:frontend

      - name: Test
        run: |
          mise run lint

          mise run start:server &
          SERVER_PID=$!
          sleep 5
          kill -INT $SERVER_PID

      - if: |
          github.repository_owner == 'jspaste' &&
          ((github.event_name == 'pull_request' && !startsWith(steps.ctx.outputs.branch, 'renovate/') && !startsWith(steps.ctx.outputs.branch, 'gh-readonly-queue/')) ||
          (github.event_name == 'merge_group' && startsWith(steps.ctx.outputs.branch, 'gh-readonly-queue/dev/')))
        name: Upload frontend build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: "build-frontend"
          path: "./dist/frontend/"
          if-no-files-found: "error"
          retention-days: "1"
          compression-level: "0"

  preview:
    if: |
      github.repository_owner == 'jspaste' &&
      ((github.event_name == 'pull_request' && !startsWith(needs.test.outputs.branch, 'renovate/') && !startsWith(needs.test.outputs.branch, 'gh-readonly-queue/')) ||
      (github.event_name == 'merge_group' && startsWith(needs.test.outputs.branch, 'gh-readonly-queue/dev/')))
    name: Preview
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          egress-policy: audit

      - name: Download frontend build
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: "build-frontend"
          path: "./dist/frontend/"

      - name: Deploy preview
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_TOKEN }}
          command: >-
            pages deploy ./dist/frontend
            --project-name=jspaste
            --branch="${{ github.event_name == 'pull_request' && github.event.pull_request.number || 'dev' }}"
            --commit-hash="${{ needs.test.outputs.sha }}"
            --commit-message="${{ needs.test.outputs.sha }}"
