name: 'Container'

on:
    # TODO: Remove workflow_dispatch
    workflow_dispatch:
    push:
        branches: [stable]

jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
            packages: write
