# TODO: Experimental feature, not ready for production
name: 'Container'

on:
    workflow_dispatch:
#    push:
#        branches: [stable]

jobs:
    build:
        runs-on: ubuntu-22.04
        permissions:
            contents: read
            packages: write

        env:
            IMAGE_REGISTRY: 'ghcr.io/${{ github.repository_owner }}'
            IMAGE_NAME: 'frontend'
            IMAGE_TAG: 'experimental ${{ github.sha }}'

        steps:
            - uses: actions/checkout@v4

            - name: 'Build Image'
              id: build_image
              uses: redhat-actions/buildah-build@v2
              with:
                  containerfiles: ./Containerfile
                  image: ${{ env.IMAGE_NAME }}
                  tags: ${{ env.IMAGE_TAG }}
                  oci: false

            - name: 'Push To GHCR'
              uses: redhat-actions/push-to-registry@v2
              env:
                  REGISTRY_USER: ${{ github.actor }}
                  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
              with:
                  image: ${{ steps.build_image.outputs.image }}
                  tags: ${{ steps.build_image.outputs.tags }}
                  registry: ${{ env.IMAGE_REGISTRY }}
                  username: ${{ env.REGISTRY_USER }}
                  password: ${{ env.REGISTRY_PASSWORD }}
