name: 'CI/Prettify'
on:
    workflow_dispatch:
    pull_request:
        branches: ['stable']
        types: ['opened', 'synchronize']

concurrency:
    group: '${{ github.workflow }}-${{ github.ref }}'
    cancel-in-progress: true

permissions:
  contents: read

jobs:
    prettify:
        name: 'Prettify code'
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@v2
              with:
                egress-policy: audit

            - name: 'Checkout'
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}

            - name: 'Setup package manager'
              uses: pnpm/action-setup@v2
              with:
                  standalone: true

            - name: 'Setup dependencies'
              run: pnpm install -D --frozen-lockfile --ignore-scripts

            - name: 'Run Prettier'
              uses: creyD/prettier_action@v4.3
              with:
                  prettier_options: . --write
                  same_commit: true
