# TODO: Experimental feature
name: 'CI -> Security-Dependencies'
on: [pull_request]

permissions:
    contents: read

jobs:
    dependency-review:
        name: 'Dependency analysis'
        runs-on: ubuntu-latest
        steps:
            - name: 'Harden Runner'
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: audit

            - name: 'Checkout'
              uses: actions/checkout@v4
              with:
                persist-credentials: false

            - name: 'Dependency Review'
              uses: actions/dependency-review-action@v4
