name: "CI -> Test"
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".*ignore"

  pull_request:
    branches:
      - dev
    paths-ignore:
      - "*.md"
      - ".*ignore"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit

      - name: 'Checkout'
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          persist-credentials: false

      - name: "Setup dependencies"
        run: bun install --frozen-lockfile

      - name: "Run lint"
        run: bun run lint
